"""add overview and hours_per_day to plans

Revision ID: 00368ac0d202
Revises: 16b1f723d0c3
Create Date: 2026-03-26 11:33:24.043862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00368ac0d202'
down_revision: Union[str, None] = '16b1f723d0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('overview', sa.Text(), nullable=True))
    op.add_column('plans', sa.Column('hours_per_day', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'hours_per_day')
    op.drop_column('plans', 'overview')
    # ### end Alembic commands ###
