"""add_goal_jobs_table

Revision ID: 14f26f198319
Revises: e13246fdcfac
Create Date: 2026-03-26 16:47:19.542316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14f26f198319'
down_revision: Union[str, None] = 'e13246fdcfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('estimated_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_jobs_status'), 'goal_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_goal_jobs_user_id'), 'goal_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_jobs_user_id'), table_name='goal_jobs')
    op.drop_index(op.f('ix_goal_jobs_status'), table_name='goal_jobs')
    op.drop_table('goal_jobs')
    # ### end Alembic commands ###
