"""add_start_date_to_goals

Revision ID: 16b1f723d0c3
Revises: 3d6e1e6d4609
Create Date: 2026-03-09 16:26:56.756683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b1f723d0c3'
down_revision: Union[str, None] = '3d6e1e6d4609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'start_date')
    # ### end Alembic commands ###
