"""make_target_date_stake_required

Revision ID: 3d6e1e6d4609
Revises: 3bfe08c0b68a
Create Date: 2026-03-09 16:17:13.134194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6e1e6d4609'
down_revision: Union[str, None] = '3bfe08c0b68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'target_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('goals', 'stake_per_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'stake_per_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('goals', 'target_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
