"""drop_checkins_add_task_status

Revision ID: 5824200c9d75
Revises: fd97be478866
Create Date: 2026-03-26 14:58:37.548352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5824200c9d75'
down_revision: Union[str, None] = 'fd97be478866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    op.add_column('tasks', sa.Column('status', sa.Text(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    op.create_table('checkins',
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('proof_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='checkins_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='checkins_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='checkins_pkey')
    )
    # ### end Alembic commands ###
