"""add_explanation_and_guide_to_tasks

Revision ID: e13246fdcfac
Revises: 5824200c9d75
Create Date: 2026-03-26 15:42:30.344442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e13246fdcfac'
down_revision: Union[str, None] = '5824200c9d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('guide', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'guide')
    op.drop_column('tasks', 'explanation')
    # ### end Alembic commands ###
