"""add_execution_date_to_tasks

Revision ID: fd97be478866
Revises: 65bae40a8e19
Create Date: 2026-03-26 14:40:50.956815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd97be478866'
down_revision: Union[str, None] = '65bae40a8e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('execution_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_tasks_execution_date'), 'tasks', ['execution_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_execution_date'), table_name='tasks')
    op.drop_column('tasks', 'execution_date')
    # ### end Alembic commands ###
